### ISSUE TITLE
Warnings "Updating places sensor took longer than the scheduled update interval 0:00:30"

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#214] opened 2023-09-01 21:45 UTC
Have a lot of warnings like:
```
2023-09-02 00:04:56.730 WARNING (MainThread) [homeassistant.components.sensor] Updating places sensor took longer than the scheduled update interval 0:00:30
2023-09-02 00:05:26.731 WARNING (MainThread) [homeassistant.components.sensor] Updating places sensor took longer than the scheduled update interval 0:00:30
2023-09-02 00:05:56.733 WARNING (MainThread) [homeassistant.components.sensor] Updating places sensor took longer than the scheduled update interval 0:00:30
```
Polling is ON (a default settings).
I believed that the `places` entity is updated whenever an associated entity has changed `latitude` or `longitude` data.
But looking at these messages, it seems that there is some "scheduled update interval 0:00:30".
Does it mean that `places` entities are trying to update every 30 sec?

P.S. Trying to compose with info posted here: https://github.com/custom-components/places/issues/56

**Comment by Snuffy2** [comment] 2023-09-02 16:15
No `places` does not update every 30 seconds. It will update whenever the associated entity changes (but only at most once every 10 seconds as of v2.4.5) and then will also update every 10 minutes even if no entity changes. If the current location is not different from the previous location, the update doesn't proceed. The logic is essentially unchanged from what is posted in #56 except that "If there are >3 checks with distance <10m, it will proceed to next check" has since been removed as it wasn't actually doing anything with the other logic in place.

All that being said, I have also started seeing similar errors in my logs as well. Even with [debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) enabled, it is still not clear to me what is occurring. If you can [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and let me know if you are seeing anything of note it would be appreciated.

**Comment by ildar170975** [comment] 2023-09-02 16:48
Thanks a lot for the reply! I will start monitoring it as well.

**Comment by Snuffy2** [comment] 2023-09-04 23:15
Please give v2.5 a try. I tweaked the track state changes function to be more asynchronous which in my limited testing so far seems to have cleared the timeout warnings.

**Comment by ildar170975** [comment] 2023-09-05 00:04
Do not see these warnings with 2.5.
I will close the issue then & continue monitoring.
Thanks a lot!!!!

**Comment by ildar170975** [comment] 2023-09-28 22:23
Again see these warnings:
![image](https://github.com/custom-components/places/assets/71872483/af4baec6-0e4d-421a-aaef-103a0b772401)

**Comment by ildar170975** [comment] 2023-09-29 16:31
> not seeing this anymore since v2.5.

Could it depend on a particular hardware/software?
Also, I live in Russia and gov is desperately trying to isolate it from Internet, so some servers are unavailable & some have a rather unstable connection.

Enabled debug logging:
```
logger:
  default: warn
  logs:
    custom_components.sensor.places: debug
```
After HA reboot I see no these messages; only see [messages described here](https://github.com/custom-components/places/issues/212#issuecomment-1741176432).
Seems that these "longer than the scheduled update interval 0:00:30" messages may or may not come...

**Comment by Snuffy2** [comment] 2023-09-29 23:46
I'm going to close this for now. It may be, as you say, that it is intermittent due to connectivity/internet issues. I'm not really able to troubleshoot this one further unless I can either reproduce it on my end or I can get logs that show something that may be fixable. Sorry.

**Closed by Snuffy2** 2023-09-29 23:46 UTC
Labels: bug, help wanted

**Comment by ildar170975** [comment] 2023-09-30 00:00
No problem! I will keep monitoring & let you know if it happens again.

BTW - strange that nothing new was added into Log with enabled debug logging!
